services:
  quickclip:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quickclip-app
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
